INSERT INTO TIPO_DERRATE (DESCRIZIONE) VALUES ('Fresco');
INSERT INTO TIPO_DERRATE (DESCRIZIONE) VALUES ('Carne');
INSERT INTO TIPO_DERRATE (DESCRIZIONE) VALUES ('Congelati');
INSERT INTO TIPO_DERRATE (DESCRIZIONE) VALUES ('Scatolati');
INSERT INTO TIPO_DERRATE (DESCRIZIONE) VALUES ('Bevande');

INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Bieta', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Spinaci', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Pomodori', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Carote', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Melanzane', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Peperoni', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Zucchine', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Insalata', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Latte', 'Lt', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Cipolle', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 1);

INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Fettine vitello', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 2);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Spezzatino manzo', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 2);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Braciole Maiale', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 2);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Macinato vitello', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 2);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Salsicce maiale', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 2);

INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Piselli', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 3);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Nasello', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 3);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Merluzzo', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 3);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Fave', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 3);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Minestrone', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 3);

INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ( 'Fagioli', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 4);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Lenticchie', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 4);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Mais', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 4);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Tonno', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 4);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Ceci', 'Kg', 1.5, 5, CURRENT_TIMESTAMP, 1, 1, 4);

INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Acqua naturale', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Acqua frizzante', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Coca Cola', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Aranciata', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Sprite', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Te'' al limone', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Te'' alla pesca', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Chinotto', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Limonata', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);
INSERT INTO DERRATA (DESCRIZIONE_DERRATA, UNITA_MISURA, PREZZO, GIACENZA, DATA_AGGIORNAMENTO_GIACENZA, QUANTITA_MIMINA, CODICE_MENSA, TIPO_DERRATA) values ('Succo di frutta alla pera', 'Lt', 1.5, 20, CURRENT_TIMESTAMP, 1, 1, 5);

INSERT INTO PREVEVAMENTO_MENSA(DATA_PRELEVAMENTO_MENSA) VALUES (CURRENT_TIMESTAMP); -- ESEGUIRE TRE VOLTE

INSERT INTO DETTAGLIO_PRELEVAMENTO(NUMERO_BUONO, DATA_DETTAGLIO_PRELEVAMENTO, DERRATA, QUANTITA) VALUES (1, CURRENT_TIMESTAMP, 11, 1);
INSERT INTO DETTAGLIO_PRELEVAMENTO(NUMERO_BUONO, DATA_DETTAGLIO_PRELEVAMENTO, DERRATA, QUANTITA) VALUES (2, CURRENT_TIMESTAMP, 21, 2);
INSERT INTO DETTAGLIO_PRELEVAMENTO(NUMERO_BUONO, DATA_DETTAGLIO_PRELEVAMENTO, DERRATA, QUANTITA) VALUES (3, CURRENT_TIMESTAMP, 26, 3);

INSERT INTO TIPO_MOVIMENTO(TIPO_DESCRIZIONE, SEGNO) VALUES ('Prelevamento', '-');
INSERT INTO TIPO_MOVIMENTO(TIPO_DESCRIZIONE, SEGNO) VALUES ('Approvigionamento', '+');
INSERT INTO TIPO_MOVIMENTO(TIPO_DESCRIZIONE, SEGNO) VALUES ('Giacenza', '+');

INSERT INTO ENTE VALUES(1);
INSERT INTO ENTE VALUES(2);
INSERT INTO ENTE VALUES(3);

INSERT INTO FORNITORE(DESCRIZIONE) VALUES('Fornitore 1');
INSERT INTO FORNITORE(DESCRIZIONE) VALUES('Fornitore 2');
INSERT INTO FORNITORE(DESCRIZIONE) VALUES('Fornitore 3');

ALTER TABLE DETTAGLIO_MOVIMENTO
  RENAME COLUMN DATA TO DATA_DETTAGLIO_MOVIMENTO;

INSERT INTO TESTATA_MOVIMENTO(DATA, TIPO_MOVIMENTO, CODICE_FORNITORE, CODICE_ENTE, NUM_ORDINE_LAVORO, NOTA, TOTALE_IMPORTO, UTENTE_OPERATORE)
VALUES (CURRENT_TIMESTAMP, 1, 1, 1, 1, 'Nota', 1.5, 'Utente');

INSERT INTO DETTAGLIO_MOVIMENTO(NUM_PROGRESSIVO,DATA_DETTAGLIO_MOVIMENTO, DERRATA, QUANTITA_RICHIESTA, QUANTITA_EFFETTIVA, PREZZO_UNITARIO, TOTALE_VALORE)
VALUES (1, CURRENT_TIMESTAMP, 28, 1, 1, 1.5, 1.5);

