CREATE TABLE TIPO_DERRATE
(
	CODICE SERIAL PRIMARY KEY,
	DESCRIZIONE VARCHAR(256) NOT NULL -- Fresco / Carne / Congelati / Scatolati /Bevande
);

CREATE TABLE DERRATA
(
	DERRATA_ID SERIAL,
	DESCRIZIONE_DERRATA VARCHAR(256) NOT NULL,
	UNITA_MISURA VARCHAR(5),
	PREZZO DECIMAL(10,2),
	GIACENZA INT,
	DATA_AGGIORNAMENTO_GIACENZA TIMESTAMP,
	QUANTITA_MIMINA INT,
	CODICE_MENSA INT,
	TIPO_DERRATA INT REFERENCES TIPO_DERRATE(CODICE),
	PRIMARY KEY(DERRATA_ID)

);

CREATE TABLE PRELEVAMENTO_MENSA
(
	NUMERO_BUONO SERIAL PRIMARY KEY,
	DATA_PRELEVAMENTO_MENSA TIMESTAMP
);

CREATE TABLE dettaglio_prelevamento (
	numero_buono int4 NOT NULL,
	data_dettaglio_prelevamento timestamp NULL,
	derrata int4 NULL,
	quantita int4 NULL,
	dettaglio_prelevamento_id serial4 NOT NULL,
	CONSTRAINT dettaglio_prelevamento_pkey PRIMARY KEY (dettaglio_prelevamento_id)
);

ALTER TABLE dettaglio_prelevamento ADD CONSTRAINT dettaglio_prelevamento_derrata_fkey FOREIGN KEY (derrata) REFERENCES derrata(derrata_id);
ALTER TABLE dettaglio_prelevamento ADD CONSTRAINT dettaglio_prelevamento_numero_buono_fkey FOREIGN KEY (numero_buono) REFERENCES prelevamento_mensa(numero_buono);

CREATE TABLE TIPO_MOVIMENTO
(
	CODICE SERIAL PRIMARY KEY,
	TIPO_DESCRIZIONE VARCHAR(256), -- PRELEVAMENTO/APPROVIGIONAMENTO/GIACENZA
	SEGNO VARCHAR(1)
);

CREATE TABLE ENTE
(
	CODICE_ACED VARCHAR(6) PRIMARY KEY 
);

CREATE TABLE FORNITORE
(
	CODICE SERIAL PRIMARY KEY,
	DESCRIZIONE VARCHAR(256) NOT NULL
);

CREATE TABLE TESTATA_MOVIMENTO
(
	NUMERO_PROGRESSIVO SERIAL PRIMARY KEY,
	DATA_TESTATA_MOVIMENTO TIMESTAMP,
	TIPO_MOVIMENTO INT REFERENCES TIPO_MOVIMENTO(CODICE),
	CODICE_FORNITORE INT REFERENCES FORNITORE(CODICE),
	CODICE_ENTE VARCHAR(256) REFERENCES ENTE(CODICE_ACED),
	NUM_ORDINE_LAVORO INT,
	NOTA VARCHAR(256),
	TOTALE_IMPORTO DECIMAL(10,2),
	UTENTE_OPERATORE VARCHAR(256)
);

CREATE TABLE DETTAGLIO_MOVIMENTO
(
	ID_DETTAGLIO_MOVIMENTO SERIAL PRIMARY KEY,
	NUM_PROGRESSIVO INT NOT NULL REFERENCES TESTATA_MOVIMENTO(NUMERO_PROGRESSIVO),
	DATA_DETTAGLIO_MOVIMENTO TIMESTAMP,
	DERRATA INT REFERENCES DERRATA(DERRATA_ID),
	QUANTITA_RICHIESTA DECIMAL(5,2),
	QUANTITA_EFFETTIVA DECIMAL(5,2),
	PREZZO_UNITARIO DECIMAL(5,2),
	TOTALE_VALORE DECIMAL (5,2)
);

