CREATE TABLE TIPO_DERRATE
(
	CODICE SERIAL PRIMARY KEY,
	DESCRIZIONE VARCHAR(256) NOT NULL -- Fresco / Carne / Congelati / Scatolati /Bevande
);

CREATE TABLE DERRATA
(
	DERRATA_ID SERIAL,
	DESCRIZIONE_DERRATA VARCHAR(256) NOT NULL,
	UNITA_MISURA VARCHAR(5),
	PREZZO DECIMAL(10,2),
	GIACENZA INT,
	DATA_AGGIORNAMENTO_GIACENZA TIMESTAMP,
	QUANTITA_MIMINA INT,
	CODICE_MENSA INT,
	TIPO_DERRATA INT REFERENCES TIPO_DERRATE(CODICE),
	PRIMARY KEY(DERRATA_ID)

);

CREATE TABLE PRELEVAMENTO_MENSA
(
	NUMERO_BUONO SERIAL PRIMARY KEY,
	DATA_PRELEVAMENTO_MENSA TIMESTAMP
);

CREATE TABLE DETTAGLIO_PRELEVAMENTO
(
	NUMERO_BUONO INT REFERENCES PREVEVAMENTO_MENSA(NUMERO_BUONO), 
	DATA_DETTAGLIO_PRELEVAMENTO TIMESTAMP,
	DERRATA INT REFERENCES DERRATA(DERRATA_ID),
	QUANTITA INT,
    PRIMARY KEY(NUMERO_BUONO)
);

CREATE TABLE TIPO_MOVIMENTO
(
	CODICE SERIAL PRIMARY KEY,
	TIPO_DESCRIZIONE VARCHAR(256), -- PRELEVAMENTO/APPROVIGIONAMENTO/GIACENZA
	SEGNO VARCHAR(1)
);

CREATE TABLE ENTE
(
	CODICE_ACED VARCHAR(256) PRIMARY KEY 
);

CREATE TABLE FORNITORE
(
	CODICE SERIAL PRIMARY KEY,
	DESCRIZIONE VARCHAR(256) NOT NULL
);

CREATE TABLE TESTATA_MOVIMENTO
(
	NUMERO_PROGRESSIVO SERIAL PRIMARY KEY,
	DATA_TESTATA_MOVIMENTO TIMESTAMP,
	TIPO_MOVIMENTO INT REFERENCES TIPO_MOVIMENTO(CODICE),
	CODICE_FORNITORE INT REFERENCES FORNITORE(CODICE),
	CODICE_ENTE VARCHAR(256) REFERENCES ENTE(CODICE_ACED),
	NUM_ORDINE_LAVORO INT,
	NOTA VARCHAR(256),
	TOTALE_IMPORTO DECIMAL(10,2),
	UTENTE_OPERATORE VARCHAR(256)
);

CREATE TABLE DETTAGLIO_MOVIMENTO
(
	ID_DETTAGLIO_MOVIMENTO SERIAL PRIMARY KEY,
	NUM_PROGRESSIVO INT NOT NULL REFERENCES TESTATA_MOVIMENTO(NUMERO_PROGRESSIVO),
	DATA_DETTAGLIO_MOVIMENTO TIMESTAMP,
	DERRATA INT REFERENCES DERRATA(DERRATA_ID),
	QUANTITA_RICHIESTA DECIMAL(5,2),
	QUANTITA_EFFETTIVA DECIMAL(5,2),
	PREZZO_UNITARIO DECIMAL(5,2),
	TOTALE_VALORE DECIMAL (5,2)
);

